Thumbnails bei den Suchergebnissen, Vollauflösung beim darüber hovern mit der Maus
ReneHollander/rep0st pull request #14
Opened 2017-09-03 18:02 UTC by sm00thelf

Bei den Suchergebnissen werden jetzt Thumbnails angezeigt, und wenn man mit dem Mauszeiger drüber fährt, werden die voll aufgelösten Bilder angezeigt.

Die Lösung wurde in einer aktuellen rep0st Testumgebung getestet und hat auch ohne Probleme funktioniert!

TODO: Beim Klick auf das Bild zum entsprechenden Post auf dem pr0gramm weiterleiten.

Grüße 
sm00thelf

2017-09-03 18:19 UTC, ReneHollander commented
Schaut mal nicht so schlecht aus!

Die Verwendung ist noch etwas seltsam. Vielleicht statt dem über das Bild hovern mit eine Mausklick vergrößern? Wenn man zu einem bestimmtem Bild möchte und querfeldein fährt, wird das was man eigentlich auswählen möchte verdeckt.
Weiters kannst du Informationen zum User und Uploaddatum aus dem `search_result` nehmen. Auch Informationen mit welchem Score die Ähnlichkeit bewertet wurde findest dort.

2017-09-03 18:20 UTC, sm00thelf commented
Ok, werde ich mich morgen mal auf der Arbeit drum kümern ^^

2017-09-04 21:25 UTC, sm00thelf commented
Leider hat die Formatierung von der Schrift gerade ein bisschen gelitten, aber da werde ich mich auch nochmal dran setzen :)

2017-09-05 16:45 UTC, sm00thelf commented
So, wenn man jetzt auf den Thumbnail drückt, gibt es eine vergrößerte Ansicht. Dort hat man die Möglichkeit wieder zurück zu den Suchergebnissen zu gehen oder den Post auf dem pr0gramm anzugucken.

lg

2017-09-17 14:27 UTC, ReneHollander reviewed
Schaut echt gut aus! Wenn du die paar Kommentare bearbeitet hast werde ich Approval für den Merge geben :)

Und sorry für die lange Wartezeit. Wird hoffe ich nicht mehr vorkommen.

2017-09-17 14:27 UTC, ReneHollander commented on web/static/css/stylesheet.css
> +body, html {
Bitte mit Autoformat formatieren.

2017-09-17 14:27 UTC, ReneHollander commented on web/templates/index.html
> +    <link rel="icon" href="/static/images/rep0st-favicon.png">
Bitte `url_for` verwenden. (Wie es zuvor auch war)

2017-09-17 14:27 UTC, ReneHollander commented on web/templates/index.html
> +		<a class="lightbox" href="#{{search_result.post.image}}"> <img src="https://thumb.pr0gramm.com/{{search_result.post.image}}"/> </a>
Bitte das `thumb` Attribut vom Post Objekt (https://github.com/ReneHollander/rep0st/blob/master/rep0st/database.py#L52) verwenden. So werden auch Thumbnails bei Bildern die auf PNG enden richtig angezeigt.

2017-09-18 09:25 UTC, sm00thelf commented
Ist jetzt soweit fertig denke ich 👍

2017-09-18 17:15 UTC, ReneHollander requested changes
Danke!

2017-09-18 17:15 UTC, ReneHollander commented on web/templates/index.html
> +        src="/static/js/uploadenhance.js"></script>
Auch hier bitte `url_for`

2017-09-18 17:40 UTC, merged