URL Endpunkt hinzugefügt (Wie in https://github.com/ReneHollander/rep0st/pull/29 vorgeschlagen)
ReneHollander/rep0st pull request #30
Opened 2019-07-27 21:40 UTC by Vanilla-Chan

2019-07-27 22:00 UTC, ReneHollander reviewed
Bitte auch noch die API Dokumentation hinzufügen.
Für die error messages entsprechende Englische Nachrichten verwenden. Hier können wir ruhig etwas expliziter werden, da es ja keinem User direkt angezeigt wird.

2019-07-27 22:00 UTC, ReneHollander commented on web/site.py
> +	error_message = "Es wurde keine URL angegeben, oder die URL ist ung�ltig!"
4 Spaces statt Tabulator.

2019-07-27 22:00 UTC, ReneHollander commented on web/site.py
> +    url = request.form.get("url")
Können wir die url als Query Parameter angeben? z.B: `/api/search?url=http%3A%2F%2Fexample.net%2Fexample.png`

2019-07-27 22:00 UTC, ReneHollander commented on web/site.py
> +        if url != "":
```python
if url == "":
    return api_response(error="url parameter missing", status=400)
curr_image = get_image_from_url(url)
...

```

2019-07-27 22:00 UTC, ReneHollander commented on web/site.py
> +        else:
Else Klausel ist unnötig, da der Fehlerfall davor returned.

2019-07-27 22:00 UTC, ReneHollander commented on web/site.py
> +        return api_response(error=error_message, status=400)
Status `500`, da hier ja anscheinend ein Serverseitiger Fehler auftritt.

2019-07-27 22:03 UTC, Vanilla-Chan commented on web/site.py
> +	error_message = "Es wurde keine URL angegeben, oder die URL ist ung�ltig!"
Danke visual studio

2019-07-27 22:09 UTC, Vanilla-Chan commented on web/site.py
> +    url = request.form.get("url")
Ich weiß nicht genau wie das gehen würde.

2019-07-27 22:10 UTC, ReneHollander commented on web/site.py
> +    url = request.form.get("url")
Vielleicht ist das hilfreich: https://stackoverflow.com/questions/24892035/how-can-i-get-the-named-parameters-from-a-url-using-flask

2019-07-27 22:16 UTC, Vanilla-Chan commented on web/site.py
> +        else:
Sollte das nicht auch ein 500 fehler sein?

2019-07-27 22:18 UTC, ReneHollander commented on web/site.py
> +        else:
Ja, gut beobachtet!

2019-07-27 22:22 UTC, Vanilla-Chan commented on web/site.py
> +    url = request.args.get("url")
url als Query Parameter angeben sollte jetzt möglich sein

2019-07-27 22:23 UTC, Vanilla-Chan commented
Die anderen sachen habe ich auch umgesetzt, wenn das alles so passt würde ich die docu updaten.

2019-08-01 18:12 UTC, ReneHollander requested changes
Wenn das gefixt ist, kannst du das direkt mergen. Werde dann gleich deployen :)
Wenn du möchtest, kannst dich auch bei den Autoren im README hinzufügen, mit einem Hinweis was du gemacht hast.

Danke!

2019-08-01 18:12 UTC, ReneHollander commented on docs/api/README.md
> +  * [By image url](search_image_url.md) : `POST /api/search?url=<image link>`
HTTP Methode sollte GET sein.

2019-08-01 18:12 UTC, ReneHollander commented on .gitignore
> +/.vs/rep0st/v15
Eigene zusätzliche gitignore Einträge (wenn man an PR für andere Repositories arbeitet) einfach beim committen ausnehmen (.gitignore änderungen nicht zum Index hinzufügen/stagen und comitten), oder alternativ eine globale gitignore für die eigenen verwendeten IDEs anlegen: https://help.github.com/en/articles/ignoring-files#create-a-global-gitignore

2019-08-01 18:12 UTC, ReneHollander commented on docs/api/search_image_url.md
> +**Condition** : If there was no url or the supplied is invalid.
Eventuell statt "is invalid", "url yields no response".

2019-08-01 18:12 UTC, ReneHollander commented on docs/api/search_image_url.md
> +Searches for similar images given by the query image url.
Eigentlich suchen wir ja nicht nach der URL, sondern wir fragen die URL ab, und suchen nach dem was wir zurück bekommen. "Searches for similar images by the image returned by a GET request to the given URL".

2019-08-01 18:12 UTC, ReneHollander commented on web/site.py
> +        return api_response(error="internal server error", status=500)
Am Ende der Zeile sind ein paar Leerzeichen und Tabs. Bitte entfernen.

2019-08-01 18:12 UTC, ReneHollander commented on web/site.py
> +        if url == "":
`if not url:`, da url `None` ist, wenn es nicht gesetzt wurde.

2019-08-01 20:42 UTC, merged

2019-08-01 20:49 UTC, ReneHollander commented
Der neue API Endpoint ist online!
https://rep0st.rene8888.at/api/search?url=https%3A%2F%2Fimg.pr0gramm.com%2F2019%2F07%2F31%2F8c5e64e420e6cf48.jpg